apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-docker-entrypoint-initdb-create-tables-sql
  namespace: namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client