apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-var-lib-postgre-sql-data
  namespace: namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-client