name: Build and Deploy to GKE  
on:
  push:
    branches:
      - gcloud/cluster-main-1
##########
env:
  PROJECT_ID: projectid
  GKE_CLUSTER: cluster
  GKE_ZONE: us-central1-p
  API_WEB_IMAGE: api-web-image



jobs:
  Build-and-Deploy-api-web-to-GKE:
    name: Build-and-Deploy-api-web-to-GKE
    runs-on: ubuntu-latest
#    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        # service_account_key: ${{ secrets.GKE_SA_KEY }}
        service_account_key: ${{ secrets.GKE_CREDENTIAL_MAIN }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_CREDENTIAL_MAIN }}


    # Building Docker image
    - name: Build web-api-image
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$API_WEB_IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push API_WEB_IMAGE to GCR
    - name: Publish web-api-image
      run: |-
        docker push "gcr.io/$PROJECT_ID/$API_WEB_IMAGE:$GITHUB_SHA"


    # Deploy api-web to the GKE cluster
    - name: Deploy web-api
      run: |-
        cd k8s/api-web
        kustomize edit set image gcr.io/PROJECT_ID/API_WEB_IMAGE:TAG=gcr.io/$PROJECT_ID/$API_WEB_IMAGE:$GITHUB_SHA
        kustomize build . | kubectl apply -f -
        cd ../../


  build-and-Deploy-fronted-web-and-db-and-redis-to-GKE:

    name: build-and-Deploy-fronted-web-and-db-and-redis-to-GKE
    runs-on: ubuntu-latest
#    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        # service_account_key: ${{ secrets.GKE_SA_KEY }}
        service_account_key: ${{ secrets.GKE_CREDENTIAL_MAIN }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_CREDENTIAL_MAIN }}

#    - name: Deploy db
#      run: |-
#        kubectl apply -f k8s/db/db-deployment.yaml
#        kubectl apply -f k8s/db/db-service.yaml

    - name: Deploy Redis
      run: |-
        kubectl apply -f k8s/redis/redis-deployment.yaml
        kubectl apply -f k8s/redis/redis-service.yaml

    # Building Docker image
    - name: Build fronted-web-image
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$FRONTED_WEB_IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          --build-arg REACT_APP_BASE_URL="$REACT_APP_BASE_URL" \
          --build-arg REACT_APP_GOOGLE_CLIENT_ID="$REACT_APP_GOOGLE_CLIENT_ID" \
          --build-arg REACT_APP_FRONTEND_URL="$REACT_APP_FRONTEND_URL" \
          ./client

    # Push FRONTED_WEB_IMAGE to GCR
    - name: Publish fronted-web-image
      run: |-
        docker push "gcr.io/$PROJECT_ID/$FRONTED_WEB_IMAGE:$GITHUB_SHA"


    # Deploy fronted-web to the GKE cluster
    - name: Deploy fronted-web
      run: |-
        cd k8s/fronted-web
        kustomize edit set image gcr.io/PROJECT_ID/FRONTED_WEB_IMAGE:TAG=gcr.io/$PROJECT_ID/$FRONTED_WEB_IMAGE:$GITHUB_SHA
        kustomize build . | kubectl apply -f -
        cd ../../
