apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-web-src-media
  namespace: namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client