apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-data
  namespace: namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client